# Generated by Django 6.0.5 on 2026-06-08 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('descriptiongame_name', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='DjangoApp.user')),
            ],
        ),
    ]
